### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a div for the area where the car will drive.
- [x] Add the image of the car to the div.
- [x] Apply necessary styling so the game looks nice.
