### ISSUE TITLE
User can accelerate and decelerate

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/driving-game#11]
## 💰 Motivation

The user should be able to control the speed of the car.

## 📐 Plan

Make the car go slower when the user presses d and faster when the user presses a.

## ✅ Task List

- [x] Create a property in the data for the current speed of the car
- [x] Adjust the moveCarForward function to update the location of the car using the number value of the current speed property
- [x] Adjust the moveCar function to increase or decrease the current speed based on whether the user pressed a or d
- [ ] Add div that shows user the current speed
- [ ] Add instructions for game controls
