### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create CSS classes to rotate the car in a specific direction
- [x] Create a data model to keep track of the current direction the car is facing
- [x] Listen for keydown events and
   - [x] Change the class of the car to the direction inputed by the user
   - [x] Update the current direction of the car in the data model
