### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location property to the model to keep track of the car's coordinates on the page
- [x] Set the car's position to absolute in relation to the background div
- [x] Listen for keydown events on the space bar
   - [x] Move the car a few pixels every 16 milliseconds
   - [x] Update the car's position in the data model
