### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a property to the data model that keeps track of whether the car has started or not
- [x] Add a condition to the moveCar function that checks if the car has already started when the user presses space and
   - [x] If the car has already started, stop the car from moving
   - [x] If the car hasn't started, make it move
