### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/driving-game#9]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Edit the moveCarForward function to respond to different car directions
   - [x] If the direction is east, add to the x-coordinate
   - [x] If the direction is west, subtract from the x-coordinate
   - [x] If the direction is north, subtract from the y-coordinate
   - [x] If the direction is south, add to the y-coordinate
